#!/bin/bash

RHOME=`pwd`

BIN=$RHOME/src/redis-server
PATH_PID=$RHOME/PID

#******
# starting binary checking
#******
binary_check(){
  _cat=`which cat`
  if [ ! -x $_cat ]; then 
    echo "cat not exists! ($_cat)"
    exit 1
  fi

  _wc=`which wc`
  if [ ! -x $_wc ]; then
    echo "wc not exists! ($_wc)"
    exit 1
  fi

  _rm=`which rm`
  if [ ! -x $_rm ]; then
    echo "rm not exists! ($_rm)"
    exit 1
  fi

  _grep=`which grep`
  if [ ! -x $_grep ]; then
    echo "grep not exists! ($_grep)"
    exit 1
  fi
}

pid(){
  PN=$BIN
  PID=$(ps -ef | grep $PN | grep -v grep | head -n1 |  awk '{print $2;}')
  echo $PID > $PATH_PID
}

start_redis(){
  if [ -e $PATH_PID ]
  then
    PID=$(cat $PATH_PID)
    echo "redis is up, PID: $PID"
    exit 1
  fi
  $BIN --port 9999 >> logs/stdout.log 2>&1 &
  pid
  echo "redis starts ($PID)"
}

stop_redis(){
  PID=$(cat $PATH_PID)
  kill -9 $PID
  echo "redis ($PID) is stopped"
  rm $PATH_PID
}

case $1 in
  "start")
    binary_check
    start_redis
    ;;
  "stop")
    stop_redis
    ;;
  "restart")
    stop_redis
    binary_check
    start_redis
    ;;
  *)
    echo "Please input..."
    echo "\"$0 start\" for server launching..."
    echo "\"$0 stop\" for server stopping..."
    echo "\"$0 restart\" for server relaunching..."
esac
