#!/bin/bash

update () {
  cp keyserver_bin/bin/keyserver $TGT/keyserver_bin/bin/keyserver
  cp dn_updater $TGT/dn_updater
  cp -r keyserver_bin/util $TGT/keyserver_bin/util
  cp ip_list/bin/ip_list $TGT/ip_list/bin/ip_list
}

case $1 in
  "update")
    TGT=$2
    update
    ;;
  *)
    echo "Usage: $0 update <target dir>"
    ;;
esac
