#!/bin/bash

IL_HOME=ip_list_bin
KS_HOME=keyserver_bin
DN_HOME=dn_updater

update_keyserver () {
  sudo kill -9 $(ps aux|grep keyserver_bin/bin/keyserver|grep -v grep|awk '{print $2}')
  cp $KS_HOME/bin/keyserver $TGT/$KS_HOME/bin/keyserver
}

update_dn_updater () {
  mkdir -p $TGT/$DN_HOME
  sudo kill -9 $(ps aux|grep dn_updater/dn_updater|grep -v grep|awk '{print $2}')
  cp $DN_HOME/dn_updater $TGT/$DN_HOME/dn_updater
}

update_updater () {
  sudo kill -9 $(ps aux|grep util/updater|grep -v grep|awk '{print $2}')
  cp keyserver_bin/util/updater $TGT/$KS_HOME/util/updater
}

update_ip_list () {
  sudo kill -9 $(ps aux|grep ip_list_bin/bin/ip_list|grep -v grep|awk '{print $2}')
  cp $IL_HOME/bin/ip_list $TGT/$IL_HOME/bin/ip_list
}

update_all () {
  update_keyserver
  update_ip_list
  update_dn_updater
  update_updater
}

echo_usage () {
  echo "Usage: $0 <target dir> < all | keyserver | ip_list | dn_updater | updaater >"
}

case $2 in
  "all")
    TGT=$1
    update_all
    ;;
  "keyserver")
    TGT=$1
    update_keyserver
    ;;
  "ip_list")
    TGT=$1
    update_ip_list
    ;;
  "dn_updater")
    TGT=$1
    update_dn_updater
    ;;
  "updater")
    TGT=$1
    update_updater
    ;;
  *)
    echo_usage
    ;;
esac
