#!/bin/bash

IL_HOME=ip_list_bin
KS_HOME=keyserver_bin

update () {
  cp $KS_HOME/bin/keyserver $TGT/$KS_HOME/bin/keyserver
  cp dn_updater $TGT/dn_updater
  cp -r keyserver_bin/util $TGT/$KS_HOME/util
  cp $IL_HOME/bin/ip_list $TGT/$IL_HOME/bin/ip_list
}

case $1 in
  "update")
    TGT=$2
    update
    ;;
  *)
    echo "Usage: $0 update <target dir>"
    ;;
esac
