#!/bin/bash
DP_HOME=`pwd`
KS_HOME=$DP_HOME/keyserver_bin
DN_HOME=$DP_HOME/dn_updater

deploy_ks() {
  cd $KS_HOME
  ./configure init $SEED $RAN_ID
  ./configure conf $WATCHLIST $ACC_HOME $BROKERS
}

deploy_dn_updater() {
  cd $DN_HOME
  ./configure updater $WATCHLIST $HOST $BROKERS $ETCD $REDIRECT
}

echo_usage () {
  echo "Usage: "
  echo "$0 keyserver <path to watchlist> <keygen seed> <random ID mapping: true|false> <path to accelerator directory (which contains conf/ and sbin/)>"
  echo "$0 dn_updater <host ip> <broker list seperated by comma> <etcd ip:port> <redirect IP>"
}

case $1 in
  "keyserver")
    if [ "$#" -ne 5 ]; then
      echo "Illegal number of parameters, expected 5, got $#"
    else
      SEED=$3
      RAN_ID=$4
      WATCHLIST=$2
      ACC_HOME=$5
    fi
    deploy_ks
    ;;
  "dn_updater")
    if [ "$#" -ne 6 ]; then
      echo "Illegal number of parameters, expected 6, got $#"
      echo_usage
    else
      WATCHLIST=$2
      HOST=$3
      BROKERS=$4
      ETCD=$5
      REDIRECT=$6
      deploy_dn_updater 
    fi
    ;;
  *)
    echo_usage
    ;;
esac

