#!/bin/bash

KS_HOME=`pwd`
PATH_PID=$KS_HOME/PID
KS_BIN=$KS_HOME/bin/keyserver
PATH_KWPID=$KS_HOME/KWPID
KW_BIN=$KS_HOME/bin/kswatcher

binary_check(){
  _cat=`which cat`
  if [ ! -x $_cat ]; then 
    echo "cat not exists! ($_cat)"
    exit 1
  fi

  _wc=`which wc`
  if [ ! -x $_wc ]; then
    echo "wc not exists! ($_wc)"
    exit 1
  fi

  _rm=`which rm`
  if [ ! -x $_rm ]; then
    echo "rm not exists! ($_rm)"
    exit 1
  fi

  _awk=`which awk`
  if [ ! -x $_awk ]; then
    echo "awk not exists! ($_awk)"
    exit 1
  fi

  _grep=`which grep`
  if [ ! -x $_grep ]; then
    echo "grep not exists! ($_grep)"
    exit 1
  fi
}

kw_stop(){
  KWPID=$(cat $PATH_KWPID)
  kill -9 $KWPID
  echo "Keyserver Watcher ($KWPID) is stopped"
  rm -f $PATH_KWPID
}

pid(){
  KWPN=$KW_BIN
  KWPID=$(ps -ef | grep $KWPN | grep -v grep | head -n1 |  awk '{print $2;}')
  echo $KWPID > $PATH_KWPID
}

kswatcher() {
  $KW_BIN start &
  pid
  echo "Keyserver Watcher ($KWPID) started!"
}

case $1 in 
  "start")
    binary_check
    kswatcher
    ;;
  "stop")
    binary_check
    kw_stop
    ;;
  "restart")
    binary_check
    kw_stop
    kswatcher
    ;;
  *)
    echo "Usage: $0 [start|stop|restart]"
    ;;
esac
exit 0
